# Generated by Django 5.1.3 on 2025-01-02 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_application_standardized_tests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='dob',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AlterField(
            model_name='application',
            name='signdate',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1), null=True),
        ),
    ]
