# Generated by Django 5.1.3 on 2025-01-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_dob_alter_application_signdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='stage_1_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='stage_2_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='stage_3_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='stage_4_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='stage_5_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='stage_6_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
