# Generated by Django 5.1.3 on 2025-01-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_stage_1_data_application_stage_2_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='stage_7_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
