# Generated by Django 5.1.3 on 2025-01-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_stage_7_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='stage_1_data',
        ),
        migrations.RemoveField(
            model_name='application',
            name='stage_2_data',
        ),
        migrations.RemoveField(
            model_name='application',
            name='stage_3_data',
        ),
        migrations.RemoveField(
            model_name='application',
            name='stage_4_data',
        ),
        migrations.RemoveField(
            model_name='application',
            name='stage_5_data',
        ),
        migrations.RemoveField(
            model_name='application',
            name='stage_6_data',
        ),
        migrations.RemoveField(
            model_name='application',
            name='stage_7_data',
        ),
    ]
