# Generated by Django 5.1.4 on 2025-01-06 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_remove_application_stage_1_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='par1_jobbusy',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='par1_levedu',
            field=models.CharField(choices=[('Primary', 'Primary education'), ('Secondary', 'Secondary Education'), ('HighSchool', 'High School or Vocational training education'), ('BachelorDeg', 'Bachelors degree or equivalent level'), ('MastersDeg', 'Masters degree or equivalent level'), ('PhD', 'PhD')], default='PhD', max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='par1_retire',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1), null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='par1_served',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
