# Generated by Django 5.1.4 on 2025-01-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_application_par1_jobbusy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='form_4_holiday',
            field=models.TextField(blank=True, null=True),
        ),
    ]
