# Generated by Django 5.1.4 on 2025-01-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_application_form_4_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='additional_circumstances_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='additional_circumstances_violation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='cohort',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='fav_hobby',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='has_passport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='known_tansaf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='other_sources_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='owns_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='passport_purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_maker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
