# Generated by Django 5.1.4 on 2025-01-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_application_additional_circumstances_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='additional_circumstances_violation',
            new_name='additional_circumstances',
        ),
        migrations.RemoveField(
            model_name='application',
            name='signed',
        ),
    ]
