# Generated by Django 5.1.4 on 2025-01-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_rename_additional_circumstances_violation_application_additional_circumstances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='signed',
            field=models.BooleanField(default=False),
        ),
    ]
