# Generated by Django 5.1.4 on 2025-01-09 05:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_remove_application_dependents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='known_tansaf',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='other_sources_details',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='signature',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
