# Generated by Django 5.1.4 on 2025-01-09 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_alter_application_known_tansaf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependent',
            old_name='name',
            new_name='dependent_name',
        ),
        migrations.RenameField(
            model_name='distinction',
            old_name='name',
            new_name='distinction_name',
        ),
        migrations.RenameField(
            model_name='sibling',
            old_name='name',
            new_name='sibling_name',
        ),
    ]
