# Generated by Django 5.1.5 on 2025-01-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_application_place_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='par1_jobtitle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
