# Generated by Django 5.1.5 on 2025-01-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_application_par1_employmentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='par2_employmentstatus',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='par2_jobtitle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
