# Generated by Django 5.1.5 on 2025-01-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_application_par2_employmentstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='report_other_adv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='report_other_olv',
            field=models.BooleanField(default=False),
        ),
    ]
