# Generated by Django 5.1.5 on 2025-01-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_application_report_other_adv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='report_other_par',
            field=models.BooleanField(default=False),
        ),
    ]
