# Generated by Django 5.1.5 on 2025-01-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_application_report_other_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='par1_degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='par1_degreeyear',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='par2_degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='par2_degreeyear',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
