# Generated by Django 5.1.5 on 2025-01-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_application_par1_degree_application_par1_degreeyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='par1_degreeyear',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='application',
            name='par2_degreeyear',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
