# Generated by Django 5.1.5 on 2025-01-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_alter_application_par1_degreeyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sibling',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
