# Generated by Django 5.1.5 on 2025-01-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0024_alter_sibling_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='suprtc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
