# Generated by Django 5.1.5 on 2025-01-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0025_alter_application_suprtc'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='home_fees',
            field=models.BooleanField(default=False),
        ),
    ]
