# Generated by Django 5.1.5 on 2025-01-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0026_application_home_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_descr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
