# Generated by Django 5.1.5 on 2025-01-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0028_activity_outside_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_descr',
            new_name='activity_description',
        ),
    ]
