# Generated by Django 5.1.5 on 2025-01-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0029_rename_activity_descr_activity_activity_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distinction',
            old_name='level',
            new_name='level_of_rec',
        ),
        migrations.AddField(
            model_name='distinction',
            name='year',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
