# Generated by Django 5.1.5 on 2025-01-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0031_application_eng_date_application_eng_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='other_sources_details',
        ),
        migrations.AddField(
            model_name='application',
            name='known_tansaf_fam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='known_tansaf_fb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='known_tansaf_ig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='known_tansaf_int',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='known_tansaf_tans',
            field=models.BooleanField(default=False),
        ),
    ]
