# Generated by Django 5.1.5 on 2025-01-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0032_remove_application_other_sources_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='known_tansaf',
        ),
        migrations.AddField(
            model_name='application',
            name='known_tansaf_other',
            field=models.BooleanField(default=False),
        ),
    ]
