# Generated by Django 5.1.5 on 2025-01-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0033_remove_application_known_tansaf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='known_tansaf_other_write',
            field=models.BooleanField(default=False),
        ),
    ]
