# Generated by Django 5.1.5 on 2025-01-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0040_application_activities_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='essay',
            field=models.BooleanField(default=False),
        ),
    ]
