# Generated by Django 5.1.5 on 2025-01-23 15:04

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0041_application_essay'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='files_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='official_id',
            field=models.FileField(blank=True, null=True, upload_to=applications.models.user_upload_path),
        ),
        migrations.AlterField(
            model_name='application',
            name='school_transcripts',
            field=models.FileField(blank=True, null=True, upload_to=applications.models.user_upload_path),
        ),
        migrations.AlterField(
            model_name='application',
            name='supps',
            field=models.FileField(blank=True, null=True, upload_to=applications.models.user_upload_path),
        ),
    ]
