# Generated by Django 5.1.5 on 2025-01-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0043_activity_weeksperyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='activity',
            name='leadership_position',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='organization_name',
            field=models.CharField(blank=True, max_length=5005, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='adv_curriculum',
            field=models.CharField(choices=[('NECTA', 'NECTA'), ('IB', 'IB'), ('CAMBRIDGE', 'Cambridge'), ('OTHER', 'Other')], max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='adv_school_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='eng_score',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='eng_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='f_payer_alevel',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='f_payer_olevel',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='known_tansaf_other_write',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='last_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='middle_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='nationality',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='olv_curriculum',
            field=models.CharField(choices=[('NECTA', 'NECTA'), ('IB', 'IB'), ('CAMBRIDGE', 'Cambridge'), ('OTHER', 'Other')], max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='olv_school_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='other_adv_curriculum',
            field=models.CharField(blank=True, choices=[('NECTA', 'NECTA'), ('IB', 'IB'), ('CAMBRIDGE', 'Cambridge'), ('OTHER', 'Other')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='other_adv_school_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='other_olv_curriculum',
            field=models.CharField(blank=True, choices=[('NECTA', 'NECTA'), ('IB', 'IB'), ('CAMBRIDGE', 'Cambridge'), ('OTHER', 'Other')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='other_olv_school_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='par1_degree',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='par1_employmentstatus',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='par1_fname',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='par1_institute',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='par1_jobbusy',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='par1_jobtitle',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='par1_levedu',
            field=models.CharField(choices=[('Primary', 'Primary education'), ('Secondary', 'Secondary Education'), ('HighSchool', 'High School or Vocational training education'), ('BachelorDeg', 'Bachelors degree or equivalent level'), ('MastersDeg', 'Masters degree or equivalent level'), ('PhD', 'PhD')], default='PhD', max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='par1_lname',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='par1_mname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='par2_degree',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='par2_employmentstatus',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='par2_fname',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='par2_institute',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='par2_jobbusy',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='par2_jobtitle',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='par2_levedu',
            field=models.CharField(choices=[('Primary', 'Primary education'), ('Secondary', 'Secondary Education'), ('HighSchool', 'High School or Vocational training education'), ('BachelorDeg', 'Bachelors degree or equivalent level'), ('MastersDeg', 'Masters degree or equivalent level'), ('PhD', 'PhD')], default='PhD', max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='par2_lname',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='par2_mname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_maker',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_model',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='place_of_birth',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='residency',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='sat_score',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='sat_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='signature',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='suprt_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='unbpayc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='dependent_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='relationship',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='distinction',
            name='distinction_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='distinction',
            name='level_of_rec',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='distinction',
            name='year',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sibling',
            name='degree',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sibling',
            name='education',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sibling',
            name='institute',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sibling',
            name='occupation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sibling',
            name='sibling_name',
            field=models.CharField(max_length=500),
        ),
    ]
