# Generated by Django 5.1.5 on 2025-01-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0044_alter_activity_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='adv_curriculum',
            field=models.CharField(choices=[('NECTA', 'NECTA'), ('IB', 'IB'), ('CAMBRIDGE', 'Cambridge'), ('OTHER', 'Other')], default='NECTA', max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='olv_curriculum',
            field=models.CharField(choices=[('NECTA', 'NECTA'), ('IB', 'IB'), ('CAMBRIDGE', 'Cambridge'), ('OTHER', 'Other')], default='NECTA', max_length=500),
        ),
    ]
