# Generated by Django 5.1.5 on 2025-01-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0045_alter_application_adv_curriculum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='form4_holiday',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Art', 'Art'), ('Athletics', 'Athletics'), ('Community Service', 'Community Service'), ('Computer/Technology', 'Computer/Technology'), ('Cultural', 'Cultural'), ('Dance', 'Dance'), ('Debate/Speech', 'Debate/Speech'), ('Environmental', 'Environmental'), ('Family Responsibilities', 'Family Responsibilities'), ('Foreign Exchange', 'Foreign Exchange'), ('Foreign Language', 'Foreign Language'), ('Journalism', 'Journalism'), ('Music: Instrumental', 'Music: Instrumental'), ('Music: Vocal', 'Music: Vocal'), ('Religious', 'Religious'), ('Research', 'Research'), ('Robotics', 'Robotics'), ('School spirit', 'School spirit'), ('Robotics', 'Robotics'), ('Science/Math', 'Science/Math'), ('Social Justice', 'Social Justice'), ('Student Govt./Politics', 'Student Govt./Politics'), ('Theatre/Drama', 'Theatre/Drama'), ('Work(Paid)', 'Work(Paid)'), ('Other Club/Activity', 'Other Club/Activity')], max_length=500),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_year',
            field=models.CharField(blank=True, choices=[('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_year',
            field=models.CharField(blank=True, choices=[('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='par1_employmentstatus',
            field=models.CharField(choices=[('Employed', 'Employed'), ('Self Employed', 'Self Employed'), ('Unemployed', 'Unemployed'), ('Retired', 'Retired')], max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='par2_employmentstatus',
            field=models.CharField(choices=[('Employed', 'Employed'), ('Self Employed', 'Self Employed'), ('Unemployed', 'Unemployed'), ('Retired', 'Retired')], max_length=500),
        ),
        migrations.AlterField(
            model_name='distinction',
            name='level_of_rec',
            field=models.CharField(choices=[('School', 'School'), ('District', 'District'), ('Regional', 'Regional'), ('National', 'National'), ('International', 'International')], max_length=500),
        ),
        migrations.AlterField(
            model_name='distinction',
            name='year',
            field=models.CharField(choices=[('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], max_length=500),
        ),
    ]
