# Generated by Django 5.1.5 on 2025-01-24 08:46

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0046_application_form4_holiday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='financial',
            field=models.FileField(blank=True, null=True, upload_to=applications.models.user_upload_path),
        ),
    ]
