# Generated by Django 5.1.5 on 2025-01-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0048_application_ib_scores_application_rec_letter1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='eng_type',
            field=models.CharField(blank=True, choices=[('TOEFL', 'TOEFL'), ('IELTS', 'IELTS'), ('Duolingo', 'Duolingo')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='sat_type',
            field=models.CharField(blank=True, choices=[('SAT', 'SAT'), ('ACT', 'ACT'), ('AP', 'AP')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sibling',
            name='education',
            field=models.CharField(choices=[('Primary', 'Primary education'), ('Secondary', 'Secondary Education'), ('HighSchool', 'High School or Vocational training education'), ('Bachelor Deg', 'Bachelors degree or equivalent level'), ('MastersDeg', 'Masters degree or equivalent level'), ('PhD', 'PhD')], default='PhD', max_length=500),
        ),
    ]
