# Generated by Django 5.1.5 on 2025-01-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0050_alter_sibling_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='par2_degreeyear',
            field=models.PositiveIntegerField(blank=True, default=2000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='par2_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='par2_employmentstatus',
            field=models.CharField(blank=True, choices=[('Employed', 'Employed'), ('Self Employed', 'Self Employed'), ('Unemployed', 'Unemployed'), ('Retired', 'Retired')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='par2_fname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='par2_jobbusy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='par2_jobtitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='par2_levedu',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary education'), ('Secondary', 'Secondary Education'), ('HighSchool', 'High School or Vocational training education'), ('BachelorDeg', 'Bachelors degree or equivalent level'), ('MastersDeg', 'Masters degree or equivalent level'), ('PhD', 'PhD')], default='PhD', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='par2_lname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='par2_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='par2_served',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
