# Generated by Django 5.1.5 on 2025-01-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0052_alter_application_dob_alter_application_eng_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
