# Generated by Django 5.1.5 on 2025-02-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0056_remove_application_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='financial_info_completed',
            field=models.BooleanField(default=False),
        ),
    ]
