# Generated by Django 5.1.5 on 2025-02-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0058_alter_application_adv_school_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='application',
            name='distinctions',
        ),
        migrations.RemoveField(
            model_name='application',
            name='form_4_holiday',
        ),
        migrations.RemoveField(
            model_name='application',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='application',
            name='unbpay',
        ),
        migrations.RemoveField(
            model_name='application',
            name='unbpayc',
        ),
        migrations.AlterField(
            model_name='application',
            name='activities_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='chlg',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='cohort',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='dependents_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='distinctions_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='extrac',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='other_inquiries_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='par1_levedu',
            field=models.CharField(choices=[('Primary', 'Primary education'), ('Secondary', 'Secondary Education'), ('High School', 'High School or Vocational training education'), ('Bachelor degree', 'Bachelors degree or equivalent level'), ('Masters Degree', 'Masters degree or equivalent level'), ('PhD', 'PhD')], default='PhD', max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='par2_levedu',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary education'), ('Secondary', 'Secondary Education'), ('High School', 'High School or Vocational training education'), ('Bachelor degree', 'Bachelors degree or equivalent level'), ('Masters Degree', 'Masters degree or equivalent level'), ('PhD', 'PhD')], default='PhD', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='siblings_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='teach',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='why_tansaf',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='why_you',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
