# Generated by Django 5.1.5 on 2025-02-06 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0059_remove_application_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='signdate',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
        ),
    ]
