# Generated by Django 5.1.5 on 2025-02-06 03:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0062_alter_application_signdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='signdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
