# Generated by Django 5.1.5 on 2025-02-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0063_alter_application_signdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='par1_retire',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='par2_retire',
            field=models.DateField(blank=True, null=True),
        ),
    ]
