# Generated by Django 5.1.5 on 2025-02-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0064_alter_application_par1_retire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='par1_degreeyear',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='par2_degreeyear',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
