# Generated by Django 5.1.5 on 2025-02-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0065_alter_application_par1_degreeyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='par1_levedu',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary education'), ('Secondary', 'Secondary Education'), ('High School', 'High School or Vocational training education'), ('Bachelor degree', 'Bachelors degree or equivalent level'), ('Masters Degree', 'Masters degree or equivalent level'), ('PhD', 'PhD')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='par2_levedu',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary education'), ('Secondary', 'Secondary Education'), ('High School', 'High School or Vocational training education'), ('Bachelor degree', 'Bachelors degree or equivalent level'), ('Masters Degree', 'Masters degree or equivalent level'), ('PhD', 'PhD')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sibling',
            name='education',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary education'), ('Secondary', 'Secondary Education'), ('High School', 'High School or Vocational training education'), ('Bachelor degree', 'Bachelors degree or equivalent level'), ('Masters', 'Masters degree or equivalent level'), ('PhD', 'PhD')], max_length=500, null=True),
        ),
    ]
