# Generated by Django 5.1.5 on 2025-02-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0066_alter_application_par1_levedu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='eng_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='sat_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
