# Generated by Django 5.1.5 on 2025-02-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0068_remove_application_essay_alter_application_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='par1_jobtitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
