# Generated by Django 5.1.5 on 2025-02-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0069_alter_application_par1_jobtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='completeapp',
            field=models.BooleanField(default=False),
        ),
    ]
