# Generated by Django 5.1.5 on 2025-02-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0070_application_completeapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='completeapp',
        ),
    ]
