# Generated by Django 5.1.5 on 2025-02-08 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0071_remove_application_completeapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='signed',
        ),
    ]
