# Generated by Django 5.1.5 on 2025-03-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0072_remove_application_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='hoursperweek',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
