# Generated by Django 5.1.5 on 2025-03-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0073_activity_hoursperweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='start_year',
            field=models.CharField(blank=True, choices=[('Grade 9', 'Grade 9/Form 3'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], max_length=500, null=True),
        ),
    ]
