# Generated by Django 5.1.5 on 2025-03-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0077_alter_distinction_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='soc_challenge',
            field=models.TextField(blank=True, null=True),
        ),
    ]
