# Generated by Django 5.1.5 on 2025-03-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0079_alter_application_sat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='sat_type',
            field=models.CharField(blank=True, choices=[('SAT', 'SAT'), ('SAT Subject Test', 'SAT Subject Test'), ('ACT', 'ACT'), ('AP', 'AP'), ('Other', 'Other')], max_length=500, null=True),
        ),
    ]
