# Generated by Django 4.2.20 on 2025-03-29 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_intern', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sibling',
            name='application',
        ),
        migrations.DeleteModel(
            name='Distinction',
        ),
        migrations.DeleteModel(
            name='Sibling',
        ),
    ]
