# Generated by Django 4.2.20 on 2025-03-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_intern', '0002_remove_sibling_application_delete_distinction_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
