# Generated by Django 4.2.20 on 2025-03-29 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_intern', '0003_delete_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sibling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sibling_name', models.CharField(blank=True, max_length=500, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('education', models.CharField(blank=True, choices=[('Primary', 'Primary education'), ('Secondary', 'Secondary Education'), ('High School', 'High School or Vocational training education'), ('Bachelor degree', 'Bachelors degree or equivalent level'), ('Masters', 'Masters degree or equivalent level'), ('PhD', 'PhD')], max_length=500, null=True)),
                ('institute', models.CharField(blank=True, max_length=500, null=True)),
                ('degree', models.CharField(blank=True, max_length=500, null=True)),
                ('occupation', models.CharField(blank=True, max_length=500, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_intern_siblings', to='application_intern.applicationintern')),
            ],
        ),
    ]
