# Generated by Django 4.2.20 on 2025-03-29 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_intern', '0005_distinction_activity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='InternActivity',
        ),
        migrations.RenameModel(
            old_name='Dependent',
            new_name='InternDependent',
        ),
        migrations.RenameModel(
            old_name='Distinction',
            new_name='InternDistinction',
        ),
        migrations.RenameModel(
            old_name='Sibling',
            new_name='InternSibling',
        ),
    ]
