# Generated by Django 4.2.20 on 2025-04-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_intern', '0006_rename_activity_internactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationintern',
            name='consider_cohort',
            field=models.BooleanField(default=False),
        ),
    ]
