# Generated by Django 5.1.5 on 2025-03-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuzzaz', '0002_remove_coordinator_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_intern',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Coordinator',
        ),
    ]
